### ISSUE TITLE
Using show=full in occs/list route gives warning

### ISSUE THREAD

**Issue by aazaff** [paleobiodb/pbdb-new#1]
Example:

https://paleobiodb.org/data1.2/occs/list.json?base_name=Cetacea&interval=Miocene&show=full
warnings: [
"undefined output block '1.2:occs:subgenus'"
],

**Comment by aazaff** [comment]
I believe @mmcclenn fixed this already. Can you confirm?

**Comment by jpjenk** [comment]
This has been corrected.
