### ISSUE TITLE
Add response "cxi" back to /colls/summary in 1.2

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/pbdb-new#17]
The value "cxi" ("cx_int_no") in responses to /colls/summary is pretty vital for Navigator. Can you please add it back to 1.2?

**Comment by mmcclenn** [comment]
This has been fixed on phylum and on teststrata. The fix has been merged into the 'master' branch on phylum, and into the currently checked out branch on teststrata.

This field is included in the result with "show=time".
