### ISSUE TITLE
interval argument to occs/diversity does not accept input

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/pbdb-new#19]
Example: [here](https://paleobiodb.org/data1.2/occs/diversity.txt?base_name=Dinosauria&continent=NOA&count=genera&interval_id=2) returns error message:

"Warning:","unknown interval id 'ARRAY(0x7fcf5f838610)'"

**Comment by mmcclenn** [comment]
This has been fixed on phylum and teststrata. The fix has been merged with 'master' on phylum, and with the current branch on teststrata.
