### ISSUE TITLE
duplicated ref numbers

### ISSUE THREAD

**Issue by SaraVarela** [paleobiodb/pbdb-new#2]
Hi, 
queries have been returning duplicated reference numbers.
best, 
Sara

**Comment by cambro** [comment]
can you give a bit more information? example URLs?

**Comment by SaraVarela** [comment]
yes, sure

https://paleobiodb.org/data1.1/occs/list.json?base_name=Mammalia&limit=1&vocab=pbdb&show=phylo,coords

you get an array of a duplicated reference_no
"reference_no":[289,289]

best regards, 
Sara

**Comment by SaraVarela** [comment]
Hi Shanan, 
I just realize that you have changed the API to version data1.2... How stable is going to be this new version? What are your plans for the API? It will change a lot in the next years? (just to know if we should adjust the package to the version 1.2 or wait until a stable "final" version of the API is ready). 
thanks for your help, 
best, 
Sara

**Comment by mmcclenn** [comment]
You're right, that's an error.  I will let you know as soon as it is fixed.

  -- Michael

**Comment by mmcclenn** [comment]
Hi Sara,

I am making some final tweaks to 1.2, and I will declare it stable within the next month or so.  At that point, I would suggest updating the package to use 1.2.  I will make sure to let you know.

  -- Michael

**Comment by SaraVarela** [comment]
Ok. 
Thanks Michael! 
best, 
Sara
