### ISSUE TITLE
Can't access paleobiodb.org

### ISSUE THREAD

**Issue by PatHolroyd** [paleobiodb/pbdb-new#4]
Using either Chrome or Firefox on Windows got a security certificate error.  From Firefox: 

paleobiodb.org uses an invalid security certificate.

The certificate expired on 4/3/2016 4:59 PM. The current time is 4/3/2016 5:55 PM.

(Error code: sec_error_expired_certificate)

**Comment by cambro** [comment]
Apologies...cert in-hand but failed to update. resolved now. Thanks for the quick issue post.
